export const CAPABILITIES: string[] = [
  "Music tailored to your audience",
  "Professional sound + lighting",
  "MC and microphone support",
  "Coordination with venues and planners",
];

/**
 * A union rather than one optional-heavy shape, so a video entry cannot be
 * declared without a poster. The poster is what holds the tile before playback,
 * and every video is `preload="none"` - without one the tile is a black box
 * until someone hovers it.
 *
 * Assets are generated by `node scripts/build-media.mjs` from masters that are
 * gitignored. See DESIGN.md > Media.
 */
export type GalleryItem =
  | { kind: "image"; label: string; src: string; alt: string }
  | { kind: "video"; label: string; src: string; poster: string; alt: string };

/** Alternates video and still so the strip never stacks two clips side by side. */
export const GALLERY: GalleryItem[] = [
  {
    kind: "video",
    label: "nightlife",
    src: "/media/club-set.mp4",
    poster: "/media/club-set.jpg",
    alt: "KNWLDG mid-set in a club under coloured lighting",
  },
  {
    kind: "image",
    label: "venue",
    src: "/media/branded-event.jpg",
    alt: "KNWLDG playing a branded event with a sponsor backdrop",
  },
  {
    kind: "video",
    label: "performance",
    src: "/media/booth-performance.mp4",
    poster: "/media/booth-performance.jpg",
    alt: "KNWLDG behind the decks with projection visuals filling the wall",
  },
  {
    kind: "image",
    label: "experience",
    src: "/media/archival-booth.jpg",
    alt: "An early photograph of KNWLDG on the microphone at a mixer",
  },
  {
    kind: "video",
    label: "equipment",
    src: "/media/deck-closeup.mp4",
    poster: "/media/deck-closeup.jpg",
    alt: "Close view of the controller, cue pads lit across the deck",
  },
];
